### ISSUE TITLE
[Bazel CI] Stardoc: Error: 'struct' has no field 'AppleDynamicFramework'


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/stardoc#260]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4254#019309f8-a35f-457c-9ae1-12aca3befc72

 Platform: MacOS

 Logs: 
```
Error: 'struct' value has no field or method 'AppleDynamicFramework'

``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/stardoc
git reset 46fd77a446f00faddedd0467ce993b462fba3c8a  --hard
export USE_BAZEL_VERSION=1c47c9d412b29f7ba42c190e0b211a9438a81d59
bazel build //... 
 ``` 
 CC Greenteam @mai93

**Comment by brentleyjones** [comment]
https://github.com/bazelbuild/stardoc/pull/259

**Comment by tetromino** [comment]
Fixed by #259

**Comment by sgowroji** [comment]
[https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4264#019323b6-1594-4282-af72-bc5f8e6afe4a](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4264#019323b6-1594-4282-af72-bc5f8e6afe4a) is still failing in Downstream today CC @brentleyjones @tetromino

**Comment by sgowroji** [comment]
CC @tetromino Can you respond on the above failures https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4388#01944e68-4167-4440-a772-8722f1942e29

**Comment by tetromino** [comment]
> CC @tetromino Can you respond on the above failures [buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4388#01944e68-4167-4440-a772-8722f1942e29](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4388#01944e68-4167-4440-a772-8722f1942e29)

@sgowroji, this was fixed by #259 (commit 91e429d9e2e959893c1ce2f81c35806b3a2daf8c).

However, the bazel-at-head-plus-downstream build you linked to was testing Stardoc at an earlier commit - 46fd77a446f00faddedd0467ce993b462fba3c8a - and of course that failed.

As far as I can see, the problem is not with Stardoc but with the fact that bazel-at-head-plus-downstream is testing an old version of Stardoc.
